(deftheme monokai
  "Created 2017-11-29.")

(custom-theme-set-variables
 'monokai
 '(ansi-color-names-vector ["#272822" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#F8F8F2"])
 '(compilation-message-face (quote default)))

(custom-theme-set-faces
 'monokai
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "coral"))))
 '(font-lock-comment-face ((t (:foreground "tomato"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 257)) (:inherit font-lock-constant-face)) (((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(button ((t (:underline t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#474747"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:inherit highlight :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit highlight :background "#3E3E3E"))))
 '(region ((((class color) (min-colors 257)) (:inherit highlight :background "#49483E")) (((class color) (min-colors 89)) (:inherit highlight :background "#474747"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:inherit region :background "#3E3D31")) (((class color) (min-colors 89)) (:inherit region :background "#3E3E3E"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#272822" :weight bold)) (((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#64645E")) (((class color) (min-colors 89)) (:foreground "#3D3D3D"))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#49483E" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#1B1E1C" :box (:line-width 1 :color "#474747" :style unspecified)))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#272822" :box (:line-width 1 :color "#64645E" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#3D3D3D" :style unspecified)))))
 '(header-line ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#49483E" :box (:color "#64645E" :line-width 1 :style unspecified))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#474747" :box (:color "#3D3D3D" :line-width 1 :style unspecified)))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#272822" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :slant italic)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(isearch ((((class color) (min-colors 257)) (:inherit region :foreground "#272822" :background "#E6DB74")) (((class color) (min-colors 89)) (:inherit region :foreground "#1B1E1C" :background "#CDC673"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:inherit isearch :foreground "#F92672" :background "#272822" :bold t)) (((class color) (min-colors 89)) (:inherit isearch :foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(ac-candidate-face ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#66D9EF")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#5FD7FF"))))
 '(ac-selection-face ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(ac-completion-face ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :underline t)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-tooltip ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-tooltip-selection ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-mouse ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(company-tooltip-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 257)) (:foreground "#272822" :background "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF" :underline t))))
 '(company-preview ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F0")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#FFFAFA"))))
 '(company-preview-common ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(company-scrollbar-bg ((((class color) (min-colors 257)) (:background "#64645E")) (((class color) (min-colors 89)) (:background "#3D3D3D"))))
 '(company-scrollbar-fg ((((class color) (min-colors 257)) (:background "#75715E")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(company-tooltip-annotation ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#A6E22E")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#87D700"))))
 '(company-template-field ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#66D9EF")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#5FD7FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#A1EFE4" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 257)) (:foreground "#75715E" :underline nil :bold nil)) (((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#A6E22E" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((t (:foreground "coral"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(ein:cell-input-area ((((class color) (min-colors 257)) (:background "#3C3D37")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(ein:cell-input-prompt ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(ein:cell-output-prompt ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(ein:notification-tab-normal ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ein:notification-tab-selected ((((class color) (min-colors 257)) (:foreground "#FD971F" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :inherit bold))))
 '(flymake-errline ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#F92672") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FEB0CC" :background "#F20055" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#870000" :background "#FF5F87" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave)) (class color) (min-colors 257)) (:underline (:style wave :color "#E6DB74") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 257)) (:foreground "#FFFACE" :background "#9A8F21" :weight bold :underline t)) (((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#878700" :background "#FFFF87" :weight bold :underline t))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#F92672"))) (((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight bold :underline t)) (((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#FF1493"))) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#FD971F"))) (((class color) (min-colors 257)) (:foreground "#FD971F" :background "#272822" :weight bold :underline t)) (((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#FF8C00"))) (((class color) (min-colors 89)) (:foreground "#FF8C00" :background "#1B1E1C" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 257)) (:underline (:style line :color "#66D9EF"))) (((class color) (min-colors 257)) (:foreground "#66D9EF" :background "#272822" :weight bold :underline t)) (((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#5FD7FF"))) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 257)) (:foreground "#FA518D" :background unspecified :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF5F87" :background unspecified :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 257)) (:foreground "#FFAC4A" :background unspecified :weight bold)) (((class color) (min-colors 89)) (:foreground "#FFAF5F" :background unspecified :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 257)) (:foreground "#92E7F7" :background unspecified :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D7FF" :background unspecified :weight bold))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#3C3D37")) (((class color) (min-colors 89)) (:background "#000000"))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#272822" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#272822" :width condensed)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(info-header-xref ((((class color) (min-colors 257)) (:foreground "#A6E22E" :inherit bold :underline t)) (((class color) (min-colors 89)) (:foreground "#87D700" :inherit bold :underline t))))
 '(info-node ((((class color) (min-colors 257)) (:foreground "#AE81FF" :inherit bold)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 257)) (:height 1.3)) (((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-2 ((((class color) (min-colors 257)) (:height 1.2)) (((class color) (min-colors 89)) (:height 1.2))))
 '(info-title-3 ((((class color) (min-colors 257)) (:height 1.15)) (((class color) (min-colors 89)) (:height 1.15))))
 '(info-title-4 ((((class color) (min-colors 257)) (:height 1.1)) (((class color) (min-colors 89)) (:height 1.1))))
 '(js2-error ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(js2-external-variable ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(js2-function-call ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(js2-function-param ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(js2-instance-member ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(js2-jsdoc-type ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(js2-jsdoc-value ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(js2-object-property ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(js2-private-function-call ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(js2-private-member ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(js2-warning ((((class color) (min-colors 257)) (:underline "#FD971F")) (((class color) (min-colors 89)) (:underline "#FF8C00"))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#8F908A" :background "#272822" :inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#8F908A" :background "#1B1E1C" :inherit default :underline nil))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :weight normal)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(mu4e-cited-1-face ((((class color) (min-colors 257)) (:foreground "#A6E22E" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :slant italic :weight normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :slant italic :weight normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic :weight normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 257)) (:foreground "#A6E22E" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :slant italic :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-flagged-face ((((class color) (min-colors 257)) (:foreground "#FD5FF0" :weight bold)) (((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(mu4e-warning-face ((((class color) (min-colors 257)) (:foreground "#F92672" :slant normal :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :slant normal :weight bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 257)) (:inherit unspecified :foreground unspecified :background "#3C3D37" :underline "#F8F8F0" :weight normal)) (((class color) (min-colors 89)) (:inherit unspecified :foreground unspecified :background "#000000" :underline "#FFFAFA" :weight normal))))
 '(mu4e-draft-face ((((class color) (min-colors 257)) (:inherit font-lock-string-face)) (((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(mu4e-footer-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mu4e-forwarded-face ((((class color) (min-colors 257)) (:inherit font-lock-builtin-face :weight normal)) (((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-header-face ((((class color) (min-colors 257)) (:inherit default)) (((class color) (min-colors 89)) (:inherit default))))
 '(mu4e-header-marks-face ((((class color) (min-colors 257)) (:inherit font-lock-preprocessor-face)) (((class color) (min-colors 89)) (:inherit font-lock-preprocessor-face))))
 '(mu4e-header-title-face ((((class color) (min-colors 257)) (:inherit font-lock-type-face)) (((class color) (min-colors 89)) (:inherit font-lock-type-face))))
 '(mu4e-highlight-face ((((class color) (min-colors 257)) (:inherit font-lock-pseudo-keyword-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-pseudo-keyword-face :weight bold))))
 '(mu4e-moved-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant italic)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-ok-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant normal :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant normal :weight bold))))
 '(mu4e-replied-face ((((class color) (min-colors 257)) (:inherit font-lock-builtin-face :weight normal)) (((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-system-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :slant italic)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-title-face ((((class color) (min-colors 257)) (:inherit font-lock-type-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-type-face :weight bold))))
 '(mu4e-trashed-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :strike-through t)) (((class color) (min-colors 89)) (:inherit font-lock-comment-face :strike-through t))))
 '(mu4e-unread-face ((((class color) (min-colors 257)) (:inherit font-lock-keyword-face :weight bold)) (((class color) (min-colors 89)) (:inherit font-lock-keyword-face :weight bold))))
 '(popup-face ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#F5F5F5"))))
 '(popup-isearch-match ((((class color) (min-colors 257)) (:background "#A6E22E")) (((class color) (min-colors 89)) (:background "#87D700"))))
 '(popup-menu-face ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#F5F5F5"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 257)) (:background "#66D9EF" :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#F5F5F5"))))
 '(popup-menu-selection-face ((((class color) (min-colors 257)) (:background "#FD5FF0" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 257)) (:background "#75715E")) (((class color) (min-colors 89)) (:background "#8B8878"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 257)) (:background "#F8F8F0")) (((class color) (min-colors 89)) (:background "#FFFAFA"))))
 '(popup-tip-face ((((class color) (min-colors 257)) (:background "#3C3D37" :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:background "#000000" :foreground "#F5F5F5"))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#A6E22E" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(speedbar-button-face ((((class color) (min-colors 257)) (:inherit default :foreground "#75715E")) (((class color) (min-colors 89)) (:inherit default :foreground "#8B8878"))))
 '(speedbar-directory-face ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF"))))
 '(speedbar-file-face ((((class color) (min-colors 257)) (:inherit default :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:inherit default :foreground "#F5F5F5"))))
 '(speedbar-highlight-face ((((class color) (min-colors 257)) (:inherit default :background "#3C3D37")) (((class color) (min-colors 89)) (:inherit default :background "#000000"))))
 '(speedbar-selected-face ((((class color) (min-colors 257)) (:inherit default :foreground "#E6DB74" :underline t)) (((class color) (min-colors 89)) (:inherit default :foreground "#CDC673" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 257)) (:inherit default :background "#66D9EF" :foreground "#272822" :overline "#4BBEAE")) (((class color) (min-colors 89)) (:inherit default :background "#5FD7FF" :foreground "#1B1E1C" :overline "#AFFFFF"))))
 '(speedbar-tag-face ((((class color) (min-colors 257)) (:inherit default :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit default :foreground "#87D700"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#FFFACE" :foreground "#272822" :inherit default))))
 '(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C")))))

(provide-theme 'monokai)
