(deftheme zenburn
  "Created 2017-11-29.")

(custom-theme-set-variables
 'zenburn
 '(ansi-color-names-vector ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#DCDCCC"]))

(custom-theme-set-faces
 'zenburn
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :weight bold))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(header-line ((t (:foreground "#F0DFAF" :background "#2B2B2B" :box (:line-width -1 :style released-button)))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(compilation-info ((t (:foreground "#BFEBBF" :underline t))))
 '(compilation-line-number ((t (:foreground "#F0DFAF"))))
 '(compilation-mode-line-exit ((t (:foreground "#9FC59F" :weight bold))))
 '(compilation-mode-line-fail ((t (:foreground "#CC9393" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#F0DFAF" :weight bold))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(Info-quoted ((t (:inherit font-lock-constant-face))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#8FB28F" :background "#2B2B2B" :box (:line-width -1 :style released-button))) (t :inverse-video t)))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#5F7F5F" :background "#383838" :box (:line-width -1 :style released-button)))))
 '(region ((((class color) (min-colors 89)) (:background "#2B2B2B")) (t :inverse-video t)))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "medium spring green"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "medium spring green"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(ac-candidate-face ((t (:background "#6F6F6F" :foreground "#000000"))))
 '(ac-selection-face ((t (:background "#4C7073" :foreground "#DCDCCC"))))
 '(popup-tip-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-menu-mouse-face ((t (:background "#D0BF8F" :foreground "#000000"))))
 '(popup-summary-face ((t (:background "#6F6F6F" :foreground "#000000"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#366060"))))
 '(popup-scroll-bar-background-face ((t (:background "#2B2B2B"))))
 '(popup-isearch-match ((t (:background "#3F3F3F" :foreground "#DCDCCC"))))
 '(company-tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(company-tooltip-annotation ((t (:foreground "#DFAF8F" :background "#4F4F4F"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#DFAF8F" :background "#2B2B2B"))))
 '(company-tooltip-selection ((t (:foreground "#DCDCCC" :background "#2B2B2B"))))
 '(company-tooltip-mouse ((t (:background "#2B2B2B"))))
 '(company-tooltip-common ((t (:foreground "#9FC59F"))))
 '(company-tooltip-common-selection ((t (:foreground "#9FC59F"))))
 '(company-scrollbar-fg ((t (:background "#2B2B2B"))))
 '(company-scrollbar-bg ((t (:background "#5F5F5F"))))
 '(company-preview ((t (:background "#9FC59F"))))
 '(company-preview-common ((t (:foreground "#9FC59F" :background "#2B2B2B"))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#BC8383") :inherit unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#F0DFAF") :inherit unspecified)) (t (:foreground "#F0DFAF" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave))) (:underline (:style wave :color "#93E0E3") :inherit unspecified)) (t (:foreground "#93E0E3" :weight bold :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#BC8383" :weight bold))))
 '(flycheck-fringe-warning ((t (:foreground "#F0DFAF" :weight bold))))
 '(flycheck-fringe-info ((t (:foreground "#93E0E3" :weight bold))))
 '(flymake-errline ((((supports :underline (:style wave))) (:underline (:style wave :color "#CC9393") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#BC8383" :weight bold :underline t))))
 '(flymake-warnline ((((supports :underline (:style wave))) (:underline (:style wave :color "#DFAF8F") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#DFAF8F" :weight bold :underline t))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#383838")) (t :weight bold)))
 '(ido-first-match ((t (:foreground "#F0DFAF" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(ido-indicator ((t (:foreground "#F0DFAF" :background "#8C5353"))))
 '(js2-warning ((t (:underline "#DFAF8F"))))
 '(js2-error ((t (:foreground "#CC9393" :weight bold))))
 '(js2-jsdoc-tag ((t (:foreground "#5F7F5F"))))
 '(js2-jsdoc-type ((t (:foreground "#9FC59F"))))
 '(js2-jsdoc-value ((t (:foreground "#AFD8AF"))))
 '(js2-function-param ((t (:foreground "#DFAF8F"))))
 '(js2-external-variable ((t (:foreground "#DFAF8F"))))
 '(js2-instance-member ((t (:foreground "#5F7F5F"))))
 '(js2-jsdoc-html-tag-delimiter ((t (:foreground "#DFAF8F"))))
 '(js2-jsdoc-html-tag-name ((t (:foreground "#BC8383"))))
 '(js2-object-property ((t (:foreground "#94BFF3"))))
 '(js2-private-function-call ((t (:foreground "#93E0E3"))))
 '(js2-function-call ((t (:foreground "#93E0E3"))))
 '(js2-private-member ((t (:foreground "#7CB8BB"))))
 '(linum ((t (:foreground "#9FC59F" :background "#3F3F3F"))))
 '(message-cited-text ((t (:inherit font-lock-comment-face))))
 '(message-header-name ((t (:foreground "#8FB28F"))))
 '(message-header-other ((t (:foreground "#7F9F7F"))))
 '(message-header-to ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-cc ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-header-subject ((t (:foreground "#DFAF8F" :weight bold))))
 '(message-header-xheader ((t (:foreground "#7F9F7F"))))
 '(message-mml ((t (:foreground "#F0DFAF" :weight bold))))
 '(message-separator ((t (:inherit font-lock-comment-face))))
 '(mu4e-cited-1-face ((t (:foreground "#8CD0D3" :slant italic))))
 '(mu4e-cited-2-face ((t (:foreground "#9FC59F" :slant italic))))
 '(mu4e-cited-3-face ((t (:foreground "#6CA0A3" :slant italic))))
 '(mu4e-cited-4-face ((t (:foreground "#7F9F7F" :slant italic))))
 '(mu4e-cited-5-face ((t (:foreground "#4C7073" :slant italic))))
 '(mu4e-cited-6-face ((t (:foreground "#5F7F5F" :slant italic))))
 '(mu4e-cited-7-face ((t (:foreground "#8CD0D3" :slant italic))))
 '(mu4e-replied-face ((t (:foreground "#6F6F6F"))))
 '(mu4e-trashed-face ((t (:foreground "#6F6F6F" :strike-through t))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:background "#6F6F6F" :weight bold))))
 '(speedbar-button-face ((t (:foreground "#9FC59F"))))
 '(speedbar-directory-face ((t (:foreground "#93E0E3"))))
 '(speedbar-file-face ((t (:foreground "#DCDCCC"))))
 '(speedbar-highlight-face ((t (:foreground "#3F3F3F" :background "#9FC59F"))))
 '(speedbar-selected-face ((t (:foreground "#CC9393"))))
 '(speedbar-separator-face ((t (:foreground "#3F3F3F" :background "#7CB8BB"))))
 '(speedbar-tag-face ((t (:foreground "#F0DFAF"))))
 '(default ((t (:foreground "#DCDCCC" :background "#3F3F3F")))))

(provide-theme 'zenburn)
